version: '3.8'
services:
  property-pros:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 8083:8083
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PropertyPros
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
  s3mock:
    image: adobe/s3mock
    restart: always
    ports:
      - '9090:9090'    
      - '9191:9191'
    environment:
      - initialBuckets=property-pros    
      - debug=true  
      - root=/data
      - trace=true
      - JAVA_TOOL_OPTIONS=-Dcom.amazonaws.sdk.disableCbor=true

    volumes:
      - ./s3mock_data:/data    
volumes:
  db:
    driver: local
