// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/google/wire"
	"github.com/vireocloud/property-pros-service/agreements"
	"github.com/vireocloud/property-pros-service/bootstrap"
	"github.com/vireocloud/property-pros-service/common"
	"github.com/vireocloud/property-pros-service/config"
	"github.com/vireocloud/property-pros-service/data"
	"github.com/vireocloud/property-pros-service/documents"
	"github.com/vireocloud/property-pros-service/interfaces"
	"github.com/vireocloud/property-pros-service/interop"
	"github.com/vireocloud/property-pros-service/server/controllers"
	"github.com/vireocloud/property-pros-service/server/interceptors"
	"github.com/vireocloud/property-pros-service/users"
)

// Injectors from main.go:

func Bootstrap() (*bootstrap.App, error) {
	iNotePurchaseAgreementModelFactory := NewNotePurchaseAgreementModelFactory()
	iAgreementsService := agreements.NewNotePurchaseAgreementService(iNotePurchaseAgreementModelFactory)
	iUserModelFactory := NewUserModelFactory()
	iUsersService := users.NewUsersService(iUserModelFactory)
	notePurchaseAgreementController := controllers.NewNotePurchaseAgreementController(iAgreementsService, iUsersService)
	authController := controllers.NewAuthController(iAgreementsService, iUsersService)
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	propertyProsApiController := interceptors.NewController(iAgreementsService, iUsersService)
	consumerDrivenContractTestingInterceptor := interceptors.NewConsumerDrivenContractTestingInterceptor(propertyProsApiController)
	authValidationInterceptor, err := provideAuthenticationInterceptor(iUsersService)
	if err != nil {
		return nil, err
	}
	grpcInterceptor := interceptors.NewGrpcInterceptor(iUsersService, consumerDrivenContractTestingInterceptor, authValidationInterceptor)
	app := bootstrap.NewApp(notePurchaseAgreementController, authController, configConfig, grpcInterceptor, authValidationInterceptor)
	return app, nil
}

func NotePurchaseAgreementInitializer() (*agreements.NotePurchaseAgreementModel, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	clientConnInterface := bootstrap.NewGrpcConnection(configConfig)
	notePurchaseAgreementServiceClient := bootstrap.NewNotePurchaseAgreementClient(clientConnInterface)
	iDocumentContentService := documents.NewDocumentContentManager(notePurchaseAgreementServiceClient)
	db, err := data.NewGormDatabase()
	if err != nil {
		return nil, err
	}
	iAgreementsRepository := data.NewAgreementsRepository(db)
	iNotePurchaseAgreementModelFactory := NewNotePurchaseAgreementModelFactory()
	iNotePurchaseAgreementGateway := agreements.NewNotePurchaseAgreementGateway(iAgreementsRepository, iNotePurchaseAgreementModelFactory)
	iUserModelFactory := NewUserModelFactory()
	iUsersService := users.NewUsersService(iUserModelFactory)
	notePurchaseAgreementModel := agreements.NewNotePurchaseAgreementModel(iDocumentContentService, iNotePurchaseAgreementGateway, iUsersService)
	return notePurchaseAgreementModel, nil
}

func UserModelInitializer() (*users.UserModel, error) {
	db, err := data.NewGormDatabase()
	if err != nil {
		return nil, err
	}
	iUsersRepository := data.NewUsersRepository(db)
	iUserModelFactory := NewUserModelFactory()
	iUsersGateway := users.NewUsersGateway(iUsersRepository, iUserModelFactory)
	userModel := users.NewUserModel(iUsersGateway)
	return userModel, nil
}

// main.go:

func main() {
	app, err := Bootstrap()
	fmt.Println("app bootstrap: ", app)
	if err != nil {
		panic(fmt.Errorf("failed to boostrap application: %w", err))
	}

	err = app.Run()

	if err != nil {
		panic(fmt.Errorf("failed to run application: %w", err))
	}

}

var UserSet wire.ProviderSet = wire.NewSet(data.NewUsersRepository, users.NewUsersGateway, users.NewUserModel, NewUserModelFactory, users.NewUsersService, controllers.NewAuthController)

var NotePuchaseAgreementSet wire.ProviderSet = wire.NewSet(data.NewAgreementsRepository, agreements.NewNotePurchaseAgreementGateway, agreements.NewNotePurchaseAgreementModel, NewNotePurchaseAgreementModelFactory, bootstrap.NewGrpcConnection, bootstrap.NewNotePurchaseAgreementClient, documents.NewDocumentContentManager, agreements.NewNotePurchaseAgreementService, controllers.NewNotePurchaseAgreementController)

var StatementSet wire.ProviderSet = wire.NewSet(data.NewStatementsRepository, controllers.NewNotePurchaseAgreementController)

func provideAuthenticationInterceptor(authService interfaces.IUsersService) (*interceptors.AuthValidationInterceptor, error) {
	return interceptors.NewAuthValidationInterceptor(authService, controllers.GRPC_AUTH_METHOD, controllers.GRPC_REGISTRATION_METHOD), nil
}

type Factory struct {
}

func (factory *Factory) NewPurchaseAgreementModel(context2 context.Context, agreement *interop.NotePurchaseAgreement) (interfaces.IAgreementModel, error) {
	agreementModel, err := NotePurchaseAgreementInitializer()

	if err != nil {
		return nil, err
	}

	agreementModel.BaseModel = common.NewBaseModel[interop.NotePurchaseAgreement](agreement, context2)
	agreementModel.SetContext(context2)
	agreementModel.SetPayload(agreement)

	return agreementModel, err
}

func NewNotePurchaseAgreementModelFactory() interfaces.INotePurchaseAgreementModelFactory {
	return &Factory{}
}

func (factory *Factory) NewUserModel(context2 context.Context, user *interop.User) (interfaces.IUserModel, error) {
	userModel, err := UserModelInitializer()
	userModel.Context = context2
	userModel.Payload = user

	return userModel, err
}

func NewUserModelFactory() interfaces.IUserModelFactory {
	return &Factory{}
}
