package interop

import (
	propertyProsAuthApi "github.com/vireocloud/property-pros-sdk/generated/auth"
	propertyProsAgreementApi "github.com/vireocloud/property-pros-sdk/generated/notepurchaseagreement"
	"google.golang.org/grpc"
)

type UnsafeNotePurchaseAgreementServiceServer = propertyProsAgreementApi.UnsafeNotePurchaseAgreementServiceServer
type UnimplementedNotePurchaseAgreementServiceServer = propertyProsAgreementApi.UnimplementedNotePurchaseAgreementServiceServer
type NotePurchaseAgreementServiceServer = propertyProsAgreementApi.NotePurchaseAgreementServiceServer

type NotePurchaseAgreement = propertyProsAgreementApi.NotePurchaseAgreement

type SaveNotePurchaseAgreementRequest = propertyProsAgreementApi.SaveNotePurchaseAgreementRequest
type SaveNotePurchaseAgreementResponse = propertyProsAgreementApi.SaveNotePurchaseAgreementResponse

type GetNotePurchaseAgreementDocRequest = propertyProsAgreementApi.GetNotePurchaseAgreementDocRequest
type GetNotePurchaseAgreementDocResponse = propertyProsAgreementApi.GetNotePurchaseAgreementDocResponse

type NotePurchaseAgreementServiceClient = propertyProsAgreementApi.NotePurchaseAgreementServiceClient

var NewNotePurchaseAgreementServiceClient = propertyProsAgreementApi.NewNotePurchaseAgreementServiceClient

var RegisterNotePurchaseAgreementServiceHandlerFromEndpoint = propertyProsAgreementApi.RegisterNotePurchaseAgreementServiceHandlerFromEndpoint
var RegisterNotePurchaseAgreementServiceServer = propertyProsAgreementApi.RegisterNotePurchaseAgreementServiceServer
var RegisterNotePurchaseAgreementServiceHandler = propertyProsAgreementApi.RegisterNotePurchaseAgreementServiceHandler

//auth
type AuthenticationServiceServer = propertyProsAuthApi.AuthenticationServiceServer
type UnsafeAuthenticationServiceServer = propertyProsAuthApi.UnsafeAuthenticationServiceServer
type UnimplementedAuthenticationServiceServer = propertyProsAuthApi.UnimplementedAuthenticationServiceServer

type User = propertyProsAuthApi.User
type AuthenticateUserRequest = propertyProsAuthApi.AuthenticateUserRequest
type AuthenticateUserResponse = propertyProsAuthApi.AuthenticateUserResponse

type AuthenticationServiceClient = propertyProsAuthApi.AuthenticationServiceClient

var NewAuthenticationServiceClient = propertyProsAuthApi.NewAuthenticationServiceClient

var RegisterAuthenticationServiceHandlerFromEndpoint = propertyProsAuthApi.RegisterAuthenticationServiceHandlerFromEndpoint
var RegisterAuthenticationServiceServer = propertyProsAuthApi.RegisterAuthenticationServiceServer

type CallOption = grpc.CallOption
